### ISSUE TITLE
MajoranaSpinor support in FCFAConvert

### ISSUE THREAD

**Issue by kirtimaan** [FeynCalc/feynhelpers#1]
Dear FeynCalc Authors,
Using FCFAConvert with a Feynarts model file that contains Majorana Fermions does not work.
It appears that MajoranaSpinor is not recognized by FeynCalc.

please advise,
best,

Kirtimaan

**Comment by vsht** [comment]
Exactly, there is currently no support for Majorana spinors. If you need that, I guess you are better off using FormCalc.
