### ISSUE TITLE
There is some directory issues on Windows system

### ISSUE THREAD

**Issue by GuojinTseng** [FeynCalc/feynhelpers#2]
When I used FIREBurn on Windows system, some errors occurred. Here is my code:
```
$LoadAddOns = {"FeynHelpers"};
<< FeynCalc`
FAD[{q, m, 4}]
FIREBurn[%, {q}, {}]
```
And my errors are:
```
Syntax::stresc :  Unknown string escape \U.
Syntax::stresc :  Unknown string escape \g.
Syntax::stresc :  Unknown string escape \A.
Syntax::stresc :  Unknown string escape \R.
Syntax::stresc :  Unknown string escape \M.
Syntax::stresc :  Unknown string escape \A.
Syntax::stresc :  Unknown string escape \F.
Syntax::sntx: Invalid syntax in or before "Get["C:\Users\guoji\AppData\Roaming\Mathematica\Applications\FIRE5\FIRE5.m"];"
                                                  ^
     (line 3 of "C:\Users\guoji\AppData\Roaming\Mathematica\Applications\FeynCalc\Database\FIREp1-int1.m").
```
As you can see, every unknown string comes from the first letter of every directory. I tried to fix this issue. I came into file 'FIREp1-int1.m' and rewrite every directory like '"C:\\Users\\guoji\\AppData\\...' and then it give me right answers with little warning. 

I tried same code on Mac and Linux system. It worked well and there was not error.

Maybe you can fix this problem. Or tell me how to deal with it. Thx!!!

**Comment by vsht** [comment]
Could you please briefly test the development version? I think that I fixed this issue there in https://github.com/FeynCalc/feynhelpers/commit/dc0566c2410a3227e4962486f2d82b1265ea97eb
but did not backport that into the stable version yet.

**Comment by vsht** [comment]
Ok, I think I fixed this issue. Please reinstall the stable version and try again.

![unbenannt](https://user-images.githubusercontent.com/7283188/37822030-4c72ab8a-2ec0-11e8-9568-090d6a862aa0.PNG)

**Comment by GuojinTseng** [comment]
Well done!!! My problem has been solved. Thank you!
