### ISSUE TITLE
var2 sign in FIREBurn result

### ISSUE THREAD

**Issue by yanghao-github** [FeynCalc/feynhelpers#3]
When I use the following orders to calculate oneloop feynman integral by FIREBurn, the result contains a strange sign "var2". And I calculate the same integral by FIRE5, confirm that var2=MC. What's more, the configure file "FIREp1.m" show that var2=MC. 
![var2-fig1](https://user-images.githubusercontent.com/49516181/70493009-502a6000-1b41-11ea-87c6-aba59edc2f4d.jpg)
![var2-fig2](https://user-images.githubusercontent.com/49516181/70493010-50c2f680-1b41-11ea-8f9c-d6056cf1cc4f.jpg)

Exit[]
$LoadAddOns = {"FeynHelpers"};
<< FeynCalc`;
ScalarProduct[p1, p1] = 4 MB^2;
ScalarProduct[p2, p2] = 0;
ScalarProduct[p1, p2] = 2 (MB^2 - MC^2);
fad = FAD[{q, MC, 2}, {q - p1, MC}, {q - p2, MC, 2}]
FIREBurn[fad, {q}, {p1, p2}]

-(((D-2) (D^2 MB^2+D^2 MC^2-11 D MB^2-10 D MC^2+31 MB^2+24 MC^2))/(64 (D-5) MC^4 (MC-MB)^3 (MB+MC)^3 ((q-p1)^2-MC^2)))-((D-2) (2 D^2 MB^4+4 D^2 MB^2 MC^2-16 D MB^4-25 D MB^2 MC^2-D MC^4+32 MB^4+26 MB^2 MC^2+4 MC^4))/(128 MC^6 (MC-MB)^3 (MB+MC)^3 (q^2-MC^2))+((D-2) (4 D^3 MB^2 var2^2+2 D^3 MC^4+4 D^2 MB^4-51 D^2 MB^2 MC^2-29 D^2 MC^4-36 D MB^4+209 D MB^2 MC^2+141 D MC^4+80 MB^4-272 MB^2 MC^2-228 MC^4))/(128 (D-5) MC^6 (MC-MB)^3 (MB+MC)^3 ((q-p2)^2-MC^2))-((D-4) (2 D MB^2-11 MB^2+MC^2))/(8 MC^2 (MC-MB)^2 (MB+MC)^2 ((q-p2)^2-MC^2).(q^2-MC^2).((q-p1)^2-MC^2))-((D-3) (2 D-11) MB^2)/(16 MC^2 (MB-MC)^3 (MB+MC)^3 (q^2-MC^2).((q-p1)^2-MC^2))

**Comment by vsht** [comment]
Thanks, should be now fixed.
